version: '3.8'

services:
  company-db:
    image: postgres:15
    container_name: company-service-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=company_service_db
    volumes:
      - ../backend/company-service/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - company-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  company-db-data: 

networks:
  myworkmanagement-network:
    external: true   